# Vendors the three type roles into the app so Foolscap renders identically with no network.
# Run once (or after changing weights); the downloaded woff2 files are committed with the app.
#   powershell -ExecutionPolicy Bypass -File scripts/fetch-fonts.ps1

$ErrorActionPreference = 'Stop'
$ua = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'
$root = Split-Path -Parent $PSScriptRoot
$outDir = Join-Path $root 'src\assets\fonts'
$keep = @('latin', 'latin-ext')

$families = @(
  @{ q = 'Schibsted+Grotesk:wght@400..700'; slug = 'schibsted-grotesk' },
  @{ q = 'IBM+Plex+Mono:wght@400;500;600';  slug = 'ibm-plex-mono' },
  @{ q = 'Caveat:wght@400..700';            slug = 'caveat' }
)

if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }

$faces = New-Object System.Collections.ArrayList
foreach ($f in $families) {
  $css = (Invoke-WebRequest -Uri "https://fonts.googleapis.com/css2?family=$($f.q)&display=swap" `
            -UserAgent $ua -UseBasicParsing).Content
  $blocks = [regex]::Matches($css, '/\*\s*(?<subset>[a-z0-9\-\[\]]+)\s*\*/\s*@font-face\s*\{(?<body>[^}]*)\}')
  foreach ($b in $blocks) {
    $subset = $b.Groups['subset'].Value
    if ($keep -notcontains $subset) { continue }
    $body = $b.Groups['body'].Value
    $family = [regex]::Match($body, "font-family:\s*'([^']+)'").Groups[1].Value
    $weight = [regex]::Match($body, 'font-weight:\s*([^;]+);').Groups[1].Value.Trim()
    $style  = [regex]::Match($body, 'font-style:\s*([^;]+);').Groups[1].Value.Trim()
    $url    = [regex]::Match($body, 'url\((https://[^)]+\.woff2)\)').Groups[1].Value
    $range  = [regex]::Match($body, 'unicode-range:\s*([^;]+);').Groups[1].Value.Trim()
    if (-not $url) { continue }

    $file = "$($f.slug)-$($subset)-$($weight -replace '\s+','-')-$style.woff2"
    Invoke-WebRequest -Uri $url -UserAgent $ua -UseBasicParsing -OutFile (Join-Path $outDir $file)
    [void]$faces.Add([pscustomobject]@{
      Family = $family; Weight = $weight; Style = $style; File = $file; Range = $range
    })
    Write-Host ("  {0,-9} {1,-22} {2}" -f $subset, "$family $weight", $file)
  }
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('/* Generated by scripts/fetch-fonts.ps1 — do not edit by hand. */')
[void]$sb.AppendLine('/* Self-hosted so the app has no network dependency at runtime. */')
foreach ($face in $faces) {
  [void]$sb.AppendLine('')
  [void]$sb.AppendLine('@font-face {')
  [void]$sb.AppendLine("  font-family: '$($face.Family)';")
  [void]$sb.AppendLine("  font-style: $($face.Style);")
  [void]$sb.AppendLine("  font-weight: $($face.Weight);")
  [void]$sb.AppendLine('  font-display: swap;')
  [void]$sb.AppendLine("  src: url('../assets/fonts/$($face.File)') format('woff2');")
  if ($face.Range) { [void]$sb.AppendLine("  unicode-range: $($face.Range);") }
  [void]$sb.AppendLine('}')
}
$cssOut = Join-Path $root 'src\styles\fonts.css'
if (-not (Test-Path (Split-Path $cssOut))) { New-Item -ItemType Directory -Path (Split-Path $cssOut) -Force | Out-Null }
[System.IO.File]::WriteAllText($cssOut, $sb.ToString())
Write-Host "`n$($faces.Count) faces -> src/styles/fonts.css"
