/**
 * Regenerates src/ui/styles.ts — the component layer's stylesheet index.
 *
 *   node scripts/ui-css.mjs        (or: npm run ui:css)
 *
 * Each primitive keeps its CSS beside its .tsx and does not import it, so the order the rules land
 * in is decided here rather than by the module graph. That matters while the port is in flight:
 * main.tsx pulls this in *after* app.css, so a component's rules win over the hand-written block
 * it supersedes.
 *
 * A TypeScript module of `import './X.css'` lines rather than a .css file of `@import`s, because a
 * plain CSS `@import` is not reliably invalidated by the dev server when the imported file changes
 * — edits went missing for three rounds before a magenta-outline probe caught it. One module per
 * stylesheet puts every file in Vite's graph, where HMR actually works.
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const uiDir = join(root, 'src', 'ui');

/** Every .css under src/ui, at any depth, excluding this file's own output. */
function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.name.endsWith('.css') && entry.name !== 'ui.css') out.push(full);
  }
  return out;
}

const files = walk(uiDir)
  .map((f) => relative(uiDir, f).split('\\').join('/'))
  .sort((a, b) => a.localeCompare(b));

const head = `/* GENERATED by scripts/ui-css.mjs — do not edit by hand. Run \`npm run ui:css\`.
   The component layer's stylesheet index, imported by main.tsx AFTER app.css so a primitive's
   rules win over the hand-written block it replaces. One import per component. */
`;

writeFileSync(
  join(uiDir, 'styles.ts'),
  head + files.map((f) => `import './${f}';`).join('\n') + '\n',
  'utf8',
);
console.log(`ui/styles.ts — ${files.length} component stylesheets`);
